[package]
edition = "2021"
name = "core"
version = "0.1.0"

[dependencies]
lazy_static = "1.4.0"
reqwest = {version = "0.11", features = ["blocking"]}

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3
strip = "debuginfo"
