name: .NET

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: | 
          8.x
          10.x
    - uses: actions/cache@v5
      id: cacheStep
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v3.1.0
    - name: Restore NuGet
      if: steps.cacheStep.outputs.cache-hit != 'true'
      run: nuget restore Octane.sln
    - name: Decode SNK and save
      shell: powershell
      run: |
        [IO.File]::WriteAllBytes("signing-key.snk", [Convert]::FromBase64String("${{ secrets.SIGNING_KEY_BASE64 }}"))    
    - name: Build
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --collect:"XPlat Code Coverage"
    - name: Upload coverage
      uses: codecov/codecov-action@v6
      with:
        files: '**/coverage.cobertura.xml'
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Delete SNK after build
      run: Remove-Item signing-key.snk
      shell: powershell
